# Generated by Django 5.1.3 on 2024-11-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
